name: docs-release-action
description: Build & Upload Docs & Release

inputs:
  revision:
    required: true
  project-name:
    required: true
  src-root:
    required: true
    default: "./"
  storage-bucket:
    required: true
  storage-endpoint:
    required: true
  storage-access-key-id:
    required: true
  storage-secret-access-key:
    required: true
  storage-region:
    required: true
  lint-root:
    default: "./_docs-lint"
  build-root:
    default: "./_docs-build"
  shared-storage-bucket:
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: Build
      uses: ./actions/build
      with:
        src-root: ${{ inputs.src-root }}
        revision: ${{ inputs.revision }}
        project-name: ${{ inputs.project-name }}
        storage-bucket: ${{ inputs.storage-bucket }}
        storage-endpoint: ${{ inputs.storage-endpoint }}
        storage-access-key-id: ${{ inputs.storage-access-key-id }}
        storage-secret-access-key: ${{ inputs.storage-secret-access-key }}
        storage-region: ${{ inputs.storage-region }}
        lint-root: ${{ inputs.lint-root }}
        build-root: ${{ inputs.build-root }}
        shared-storage-bucket: ${{ inputs.shared-storage-bucket }}
    - name: Create head folder
      shell: bash
      run: mkdir -p head
    - name: Write revision to head file
      shell: bash
      run: |
        echo "{ \"revision\": \"${{ inputs.revision }}\" }" > head/head
    - name: Set DEST_DIR
      shell: bash
      run: |
        if [ "${{ inputs.shared-storage-bucket }}" == "true" ]; then
          echo "DEST_DIR=${{ inputs.project-name }}" >> $GITHUB_ENV
        else
          echo "DEST_DIR=/" >> $GITHUB_ENV
        fi
    - name: Upload head file to storage
      shell: bash
      run: |
        yfm publish \
          -i head \
          --endpoint ${{ inputs.storage-endpoint }} \
          --region ${{ inputs.storage-region }} \
          --bucket ${{ inputs.storage-bucket }} \
          --prefix ${{ env.DEST_DIR }} \
          --access-key-id ${{ inputs.storage-access-key-id }} \
          --secret-access-key ${{ inputs.storage-secret-access-key }}